/**
 * Comprehensive Minecraft Mob list in English and Vietnamese
 */
export const MINECRAFT_MOBS: Set<string> = new Set([
	// English Mobs
	"zombie",
	"creeper",
	"skeleton",
	"spider",
	"cave spider",
	"enderman",
	"zombie pigman",
	"zombified piglin",
	"piglin",
	"piglin brute",
	"hoglin",
	"zoglin",
	"blaze",
	"ghast",
	"magma cube",
	"slime",
	"witch",
	"wither skeleton",
	"wither",
	"ender dragon",
	"guardian",
	"elder guardian",
	"shulker",
	"silverfish",
	"endermite",
	"phantom",
	"drowned",
	"husk",
	"stray",
	"pillager",
	"ravager",
	"vindicator",
	"evoker",
	"vex",
	"warden",
	"iron golem",
	"snow golem",
	"wolf",
	"polar bear",
	"panda",
	"bee",
	"dolphin",
	"pufferfish",
	"breeze",
	"bogged",

	// Vietnamese Mob Translations (2Y2C, AnarchyVN, MCVui, ViAnarchy)
	"xác sống",
	"thây ma",
	"bộ xương",
	"nhện",
	"nhện hang",
	"người ender",
	"người cõi nezer",
	"người lợn thây ma",
	"người lợn",
	"quỷ lửa",
	"bóng ma",
	"ma địa ngục",
	"khối dung nham",
	"khối chất nhờn",
	"phù thủy",
	"bộ xương wither",
	"rồng ender",
	"kẻ gác đền",
	"kẻ gác đền già",
	"cá bạc",
	"bọ ender",
	"ma trơi",
	"kẻ chết đuối",
	"xác ướp",
	"kẻ lang thang",
	"kẻ cướp",
	"kẻ tàn phá",
	"kẻ thù hằn",
	"kẻ triệu hồi",
	"quỷ lùn",
	"người sắt",
	"người tuyết",
	"chó sói",
	"gấu bắc cực",
	"ong",
	"cá nóc",
	"quái vật",
]);

/**
 * Check if a name is a known Minecraft mob (case-insensitive)
 */
export function isMinecraftMob(name: string): boolean {
	if (!name) return false;
	const clean = name.toLowerCase().trim();
	return MINECRAFT_MOBS.has(clean);
}
